name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Build
        id: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkLicenses build test runGameTest publish
          gradle-version: wrapper

      - name: Copy GameTest Results
        run: cp run/TEST-gametest.xml build/test-results/test/

      - name: Notify Discord
        uses: TeamGalacticraft/discord-reporter@main
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          outcome: ${{ steps.build.outcome }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GalacticraftAPI
          path: |
            build/libs/
            !build/libs/*-sources.jar
            !build/libs/*-dev.jar
