name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: License headers
        id: license_headers
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkLicenses

      - name: Build
        id: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Gametest
        id: gametest
        uses: gradle/gradle-build-action@v2
        with:
          arguments: runGametest
