name: Maven Publish
on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        java: [16]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: checkLicenses publish
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
        env:
          ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.MAVEN_USER }}
          ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.MAVEN_PASS }}
